### ISSUE TITLE
The code, & training Arabic recognition

### ISSUE THREAD

**Issue by ghost** [Jyouhou/ICDAR2019-ArT-Recognition-Alchemy#1]
@Jyouhou @PkuDavidGuan Thank you for your hard work,
- When do you expect to pload the code?
- Can I train to recognize non-latin scripts like Arabic which reads (from Right-to Left)?

**Comment by longshangbang** [comment]
The code will be uploaded by Sep, together with our technical reports and pre-trained models.

A building block of our method is bi-directional LSTM, which I assume can deal with different directions. :)
