### ISSUE TITLE
关于REC_SQUARE模式的问题

### ISSUE THREAD

**Issue by lijun20** [Jyouhou/ICDAR2019-ArT-Recognition-Alchemy#10]
Hi，你好，我使用了REC_SQUARE模式进行了模型的训练，当我使用REC_SQUARE模式测试同一张图片时，发现utils.py里面TextSquare函数中
aspect_ratio_augment = random.uniform(0.7, 1.3)
是一个随机数，导致每次同一张图片预测得到的结果不一样，请问我该如何解决？

**Comment by longshangbang** [comment]
这个地方之后会修正
