### ISSUE TITLE
4.img.tar.gz is not uploaded?

### ISSUE THREAD

**Issue by zobeirraisi** [Jyouhou/ICDAR2019-ArT-Recognition-Alchemy#13]
I could not find __4.img.tar.gz__ file in the uploaded IMG folder?
and also please check the size of __3.img.tar.gz__ that it has less size in comparison to others?

**Comment by longshangbang** [comment]
For 3.img.tar.gz: yes, it is smaller. 

For 4.img.tar.gz: we have re-uploaded it.
