### ISSUE TITLE
is the checkpoint right?

### ISSUE THREAD

**Issue by learn01one** [Jyouhou/ICDAR2019-ArT-Recognition-Alchemy#14]
hi,i met a problem when ran the demo:
size mismatch for rec_head.decoder.tgt_embedding.weight: copying a param with shape torch.Size([91, 256]) from checkpoint, the shape in current model is torch.Size([72, 256]).
any detaills i don't get?thanks

**Comment by longshangbang** [comment]
Which script specifically did you run?

**Comment by learn01one** [comment]
> Which script specifically did you run?

hi,the script:
./Experiment/Experiment2/Exper_2_STN_real_15_test.sh

the pretrained_model is :Real_15.pth.tar

**Comment by longshangbang** [comment]
Just try to uncomment line 33-34:

https://github.com/Jyouhou/ICDAR2019-ArT-Recognition-Alchemy/blob/29e432ed0351c2f9d1d1b15fd64ac7e83af08e3a/Source/utils/labelmaps.py#L33

It may be that the model is the one we used in IC19 competition, which contains some rare characters.

**Comment by longshangbang** [comment]
Hi @learn01one 
Did it help solve the problem?

**Comment by learn01one** [comment]
> Hi @learn01one
> Did it help solve the problem?
maybe,i met other problem:
RuntimeError: Error(s) in loading state_dict for ModelBuilder

**Comment by longshangbang** [comment]
Can you provide some more details?
