### ISSUE TITLE
About squarization and voting mechanism

### ISSUE THREAD

**Issue by heromanba** [Jyouhou/ICDAR2019-ArT-Recognition-Alchemy#15]
Hi, thanks for sharing this great work. I wonder if you can help me with the following questions:
![figure5](https://user-images.githubusercontent.com/22102769/78420186-7f7c5400-767f-11ea-8f4f-bc5f2925b12d.JPG)
1. About the effectiveness of squarization, I think it should be very useful for case "3" in the above figure. Have you counted how many images in the dataset are similar to case "3"?
2. And for case "2" and "4", I think you can rotate them based on their aspect ratios. This way they might become case "1" and "5" which seems more suitable for original preprocessing method, i.e. resize input images to 64x256. Have you tried this and compare the results with squarization?
3. About voting mechanism in ICDAR2019, what if 4 models predict totally different words? For example, model_0 predict "hello", model_1 predict "yello", model_2 predict "fello", model_1 predict "jello",  how to apply voting mechanism in this scenario?
Thanks!

**Comment by longshangbang** [comment]
Thanks for your interests! 

1. Total-Text have more such images. I didn't manually count it, but I think aspect ratios close to 1 can be an indicator. 
2. No. It is impossible to tell whether it should be rotated clockwise or anti-clockwise
3. I just randomly picked one.

**Comment by heromanba** [comment]
Hi, thanks for your reply.

About 2, I think you are right. But suppose we rotate all possible vertical arrangement words anti-clockwise, the unexpected results might be that a word is flipped like the following case.

Original             |  Rotated
:-------------------------:|:-------------------------:
![figure5_2](https://user-images.githubusercontent.com/22102769/78451705-d0a93980-76b9-11ea-94b9-f174be7bab8d.jpg)  | ![image](https://user-images.githubusercontent.com/22102769/78451865-8d9b9600-76ba-11ea-8402-6093880b0a30.png)





Will this hurt the performance of the model? I think this might be similar to the random rotation trick you mentioned in the paper.

Thanks!

**Comment by longshangbang** [comment]
That's an interesting point. I think RNNs are flexible enough to deal with it, but it is not a general solution if we consider case 3. :)

**Comment by heromanba** [comment]
Yes. Case 3 can be tricky without squarization. Thank you for your patient reply!
