### ISSUE TITLE
some problem about the code

### ISSUE THREAD

**Issue by AnddyWang** [Jyouhou/ICDAR2019-ArT-Recognition-Alchemy#7]
the function of real_multiplier?  I read the code ,but I can not understand.
anyone explains the code?   Thanks very much.

`dataset_idx = bisect.bisect_right(self.cumulative_sizes, idx)
        if dataset_idx == 0:
            sample_idx = idx
        else:
            sample_idx = idx - self.cumulative_sizes[dataset_idx - 1]
        if self.datasets[dataset_idx].real_world:
            return self.datasets[dataset_idx][sample_idx % len(self.datasets[dataset_idx])]
        return self.datasets[dataset_idx][sample_idx]`

**Comment by longshangbang** [comment]
It is used for weighted sampling of data. Please refer to the paper w.r.t. co-training with real world data.

**Comment by AnddyWang** [comment]
Ok，Thanks very much.

**Comment by PkuDavidGuan** [comment]
@AnddyWang The ConcatDataset is simply modified from the original torch.utils.data.ConcatDataset. There are ONLY TWO modifications: 1) real_multiplier. Sampling more real world data. 2) max_len. Keep all the concatenated datasets have the same max_len (which means the longest text sample.).
