### ISSUE TITLE
Environment problems

### ISSUE THREAD

**Issue by DoUMissMee** [Jyouhou/ICDAR2019-ArT-Recognition-Alchemy#9]
when I want to create the conda environment, warning and error occurs.
could you please give me advice to fix it ? thanks very much.

` conda env create -f environment.yml`

Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

CondaValueError: prefix already exists: /home/geart-jzw/anaconda3

**Comment by PkuDavidGuan** [comment]
How about change the `name` and `prefix` in the original environment.yml? Actually not many extra packages are needed in this project. You can create a virtual environment by 
```shell
conda install pytorch torchvision
```
 Then I think only tensorflow(cpu version)、editdistance are needed.

**Comment by longshangbang** [comment]
Hi @DoUMissMee ,

You should change several fields in the yml file:

`name: base`
and 
`prefix: /home/longshangbang/anaconda3/envs/SLong`
